# Python for Data Science
* [Install Python](#0)
* [Variables and Data Types](#1)
* [Python Help](#2)
* [Strings](#3)
* [Lists](#4)
* [Python Libraries](#5)
* [Numpy](#6)

![Title](python.jpg)

<a id="0"></a>
## Install Python
![Title](0.png)

<a id="1"></a>
## Variables and Data Types
![Title](1.png)

In [2]:
meyve_fiyati = 10
meyve_fiyati

10

In [10]:
# ilk ornek
elma_fiyati = 10
yeni_elma_fiyati1 = elma_fiyati + 10
yeni_elma_fiyati2 = elma_fiyati - 10
yeni_elma_fiyati3 = elma_fiyati*2
yeni_elma_fiyati4 = elma_fiyati*elma_fiyati
yeni_elma_fiyati5 = elma_fiyati**2
yeni_elma_fiyati6 = elma_fiyati%3        # 3*3 + 1 = 10
yeni_elma_fiyati7 = elma_fiyati/2
yeni_elma_fiyati7

5.0

In [ ]:
# string "dataiteam"
# int 5
# float 5.5
# boolean True, False

In [11]:
s = "merhaba"
i = 5
f = 5.5
t = True

In [14]:
s1 = str(i)
i1 = int(s1)
i1

5

In [16]:
"5" + 5

TypeError: can only concatenate str (not "int") to str

In [17]:
str(t)

'True'

In [21]:
int(5.7)

5

<a id="2"></a>
## Python Help
![Title](2.png)

In [23]:
# help(int)

<a id="3"></a>
## Strings
![Title](3.png)

In [2]:
s1 = "Yunus"
s1

'Yunus'

In [1]:
s1 = "Emre"
s1*2

'EmreEmre'

In [5]:
s1 = "Yunus"
s2 = "Emre"
s3 = s1+"_"+s2
s3

'Yunus_Emre'

In [35]:
"_" in s3

True

In [3]:
# string = lists of characters
s = "a" + "b"
s1 = "Yunus"
s1

'Yunus'

In [8]:
s1[0:5]

'Yunus'

In [7]:
s1[6:10]

''

In [6]:
s1[:]

'Yunus'

In [10]:
s2 = s1.upper()
s2

'YUNUS'

In [9]:
s2.lower()

'emre'

In [11]:
s1.count("a")

0

In [12]:
s1.replace("a","1")

'Yunus'

In [15]:
s3 = "   yunus"
s3.strip()

'yunus'

<a id="4"></a>
## Lists
![Title](4.png)

In [58]:
liste1 = ["apple","banana","cheese","water","milk"]
liste1

['apple', 'banana', 'cheese', 'water', 'milk']

In [61]:
liste1[2]

'cheese'

In [62]:
liste1[:3]

['apple', 'banana', 'cheese']

In [63]:
liste1[2:]

['cheese', 'water', 'milk']

In [67]:
liste1
liste2 = ["madrid","paris","viyana","istanbul"]
liste2
liste = [liste1, liste2]
liste

[['apple', 'banana', 'cheese', 'water', 'milk'],
 ['madrid', 'paris', 'viyana', 'istanbul']]

In [71]:
liste[1][:3]

['madrid', 'paris', 'viyana']

In [76]:
liste1 + liste2

['apple',
 'banana',
 'cheese',
 'water',
 'milk',
 'madrid',
 'paris',
 'viyana',
 'istanbul']

In [77]:
liste1*2

['apple',
 'banana',
 'cheese',
 'water',
 'milk',
 'apple',
 'banana',
 'cheese',
 'water',
 'milk']

In [80]:
liste1

['apple', 'banana', 'cheese', 'water', 'milk']

In [81]:
liste1.index('banana')

1

In [82]:
liste1.count("apple")

1

In [83]:
liste1.append("sugar")
liste1

['apple', 'banana', 'cheese', 'water', 'milk', 'sugar']

In [84]:
liste1.remove("apple")
liste1

['banana', 'cheese', 'water', 'milk', 'sugar']

In [87]:
liste1
del(liste1[1])
liste1

['banana', 'milk', 'sugar']

In [97]:
liste12 = [1,2,3,4]
liste12.reverse()
liste12

[4, 3, 2, 1]

In [98]:
liste12.extend("!")
liste12

[4, 3, 2, 1, '!']

In [101]:
liste12 = [1,2,3,4]
liste12.pop(-1)
liste12

[1, 2, 3]

In [102]:
liste12 = [1,2,3,4]
liste12.insert(2,"s")
liste12

[1, 2, 's', 3, 4]

In [106]:
liste123 = [1,6,4,2,6,8,9]
liste123.sort()
liste123

[1, 2, 4, 6, 6, 8, 9]

<a id="5"></a>
## Python Libraries
![Title](5.png)

In [107]:
import numpy as np
array1 = np.array([1,2,3])
array1

array([1, 2, 3])

<a id="6"></a>
## Numpy
![Title](6.png)

In [108]:
import numpy as np
liste1 = [1,2,3,4,5]
a1 = np.array(liste1)
a1

array([1, 2, 3, 4, 5])

In [112]:
a2 = np.array([liste1,liste1])
a2

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [113]:
a1[2]

3

In [114]:
a1[1:3]

array([2, 3])

In [115]:
a2[0,-1]

5

In [117]:
a1

array([1, 2, 3, 4, 5])

In [116]:
a1 > 3

array([False, False, False,  True,  True])

In [118]:
a1*2

array([ 2,  4,  6,  8, 10])

In [120]:
a1+a1+a1

array([ 3,  6,  9, 12, 15])

In [121]:
a1.shape

(5,)

In [122]:
a2.shape

(2, 5)

In [127]:
np.append(a1,a2)

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [128]:
a1

array([1, 2, 3, 4, 5])

In [130]:
np.insert(a1,1,4)

array([1, 4, 2, 3, 4, 5])

In [134]:
np.delete(a1,0)

array([2, 3, 4, 5])

In [136]:
a1

array([1, 2, 3, 4, 5])

In [135]:
np.mean(a1)

3.0

In [137]:
np.median(a1)

3.0

In [138]:
np.std(a1)

1.4142135623730951